import jsPDF from 'jspdf';

// Helpers
function checkPage(doc: jsPDF, y: number, needed: number = 30): number {
  if (y + needed > 275) {
    doc.addPage();
    return 20;
  }
  return y;
}

function drawFormHeader(doc: jsPDF, formNumber: string, formTitle: string, revision: string = '(2016/03)') {
  // ACORD header bar
  doc.setFillColor(0, 51, 102);
  doc.rect(10, 8, 190, 12, 'F');
  doc.setFontSize(14);
  doc.setFont('helvetica', 'bold');
  doc.setTextColor(255, 255, 255);
  doc.text(`ACORD ${formNumber}`, 15, 17);
  doc.setFontSize(9);
  doc.text(revision, 55, 17);
  doc.setFontSize(11);
  doc.text(formTitle, 105, 17, { align: 'center' });
  doc.setFontSize(7);
  doc.text('Generated by SubmissionAI', 195, 17, { align: 'right' });
  
  doc.setTextColor(0, 0, 0);
  return 28;
}

function drawSectionHeader(doc: jsPDF, title: string, y: number): number {
  y = checkPage(doc, y, 20);
  doc.setFillColor(230, 236, 245);
  doc.rect(10, y - 4, 190, 8, 'F');
  doc.setFontSize(9);
  doc.setFont('helvetica', 'bold');
  doc.setTextColor(0, 51, 102);
  doc.text(title.toUpperCase(), 14, y + 1);
  doc.setTextColor(0, 0, 0);
  return y + 10;
}

function drawField(doc: jsPDF, label: string, value: string, x: number, y: number, width: number = 85): number {
  // Field box
  doc.setDrawColor(180, 180, 180);
  doc.setLineWidth(0.3);
  doc.rect(x, y - 3, width, 12);
  
  // Label
  doc.setFontSize(6);
  doc.setFont('helvetica', 'normal');
  doc.setTextColor(100, 100, 100);
  doc.text(label, x + 2, y);
  
  // Value
  doc.setFontSize(9);
  doc.setFont('helvetica', 'bold');
  doc.setTextColor(0, 51, 102);
  const val = String(value || '');
  const truncated = val.length > Math.floor(width / 2) ? val.substring(0, Math.floor(width / 2)) + '...' : val;
  doc.text(truncated, x + 2, y + 6);
  
  doc.setTextColor(0, 0, 0);
  doc.setFont('helvetica', 'normal');
  return y + 14;
}

function drawFieldRow(doc: jsPDF, fields: {label: string, value: string}[], y: number): number {
  y = checkPage(doc, y, 18);
  const count = fields.length;
  const totalWidth = 190;
  const fieldWidth = totalWidth / count;
  
  fields.forEach((field, i) => {
    drawField(doc, field.label, field.value, 10 + (i * fieldWidth), y, fieldWidth);
  });
  
  return y + 14;
}

function drawTableHeader(doc: jsPDF, headers: string[], y: number, colWidths: number[]): number {
  y = checkPage(doc, y, 15);
  doc.setFillColor(240, 242, 247);
  doc.rect(10, y - 4, 190, 8, 'F');
  doc.setFontSize(7);
  doc.setFont('helvetica', 'bold');
  doc.setTextColor(60, 60, 60);
  
  let x = 12;
  headers.forEach((h, i) => {
    doc.text(h, x, y + 1);
    x += colWidths[i];
  });
  
  doc.setDrawColor(180, 180, 180);
  doc.line(10, y + 5, 200, y + 5);
  doc.setTextColor(0, 0, 0);
  return y + 10;
}

function drawTableRow(doc: jsPDF, cells: string[], y: number, colWidths: number[]): number {
  y = checkPage(doc, y, 10);
  doc.setFontSize(8);
  doc.setFont('helvetica', 'normal');
  
  let x = 12;
  cells.forEach((cell, i) => {
    const val = String(cell || '');
    const truncated = val.length > Math.floor(colWidths[i] / 2.5) ? val.substring(0, Math.floor(colWidths[i] / 2.5)) + '..' : val;
    doc.text(truncated, x, y);
    x += colWidths[i];
  });
  
  doc.setDrawColor(220, 220, 220);
  doc.line(10, y + 3, 200, y + 3);
  return y + 8;
}

function drawFooter(doc: jsPDF) {
  const pages = doc.getNumberOfPages();
  for (let i = 1; i <= pages; i++) {
    doc.setPage(i);
    doc.setFontSize(7);
    doc.setFont('helvetica', 'normal');
    doc.setTextColor(150, 150, 150);
    doc.text(`ACORD CORPORATION — Generated by SubmissionAI on ${new Date().toLocaleDateString()}`, 105, 290, { align: 'center' });
    doc.text(`Page ${i} of ${pages}`, 195, 290, { align: 'right' });
  }
}

// ===== ACORD 125 - COMMERCIAL INSURANCE APPLICATION =====
export function generateAcord125PDF(data: any): void {
  if (!data) return;
  const doc = new jsPDF();
  let y = drawFormHeader(doc, '125', 'COMMERCIAL INSURANCE APPLICATION');

  // Agency section
  y = drawSectionHeader(doc, 'Agency', y);
  y = drawFieldRow(doc, [
    { label: 'AGENCY NAME', value: data.agency?.name || '' },
    { label: 'PHONE', value: data.agency?.phone || '' },
  ], y);
  y = drawFieldRow(doc, [
    { label: 'ADDRESS', value: data.agency?.address || '' },
    { label: 'CITY, STATE, ZIP', value: `${data.agency?.city || ''}, ${data.agency?.state || ''} ${data.agency?.zip || ''}` },
  ], y);
  y = drawFieldRow(doc, [
    { label: 'PRODUCER CODE', value: data.agency?.producerCode || '' },
    { label: 'STATUS', value: 'Quote' },
  ], y);

  // Named Insured
  y = drawSectionHeader(doc, 'Applicant / Named Insured', y);
  y = drawFieldRow(doc, [
    { label: 'NAME (FIRST NAMED INSURED)', value: data.namedInsured?.name || '' },
    { label: 'DBA', value: data.namedInsured?.dba || '' },
  ], y);
  y = drawFieldRow(doc, [
    { label: 'MAILING ADDRESS', value: data.namedInsured?.mailingAddress || '' },
    { label: 'CITY, STATE, ZIP', value: `${data.namedInsured?.city || ''}, ${data.namedInsured?.state || ''} ${data.namedInsured?.zip || ''}` },
  ], y);
  y = drawFieldRow(doc, [
    { label: 'FEIN', value: data.namedInsured?.fein || '' },
    { label: 'ENTITY TYPE', value: data.namedInsured?.entityType || '' },
    { label: 'PHONE', value: data.namedInsured?.phone || '' },
  ], y);

  // Business Information
  y = drawSectionHeader(doc, 'Business Information', y);
  y = drawFieldRow(doc, [
    { label: 'NAICS CODE', value: data.businessInfo?.naicsCode || '' },
    { label: 'NAICS DESCRIPTION', value: data.businessInfo?.naicsDescription || '' },
  ], y);
  y = drawFieldRow(doc, [
    { label: 'YEARS IN BUSINESS', value: String(data.businessInfo?.yearsInBusiness || '') },
    { label: 'TOTAL LOCATIONS', value: String(data.businessInfo?.totalLocations || '') },
    { label: 'TOTAL EMPLOYEES', value: String(data.businessInfo?.totalEmployees || '') },
  ], y);
  y = drawFieldRow(doc, [
    { label: 'ANNUAL REVENUE', value: `$${(data.businessInfo?.totalAnnualRevenue || 0).toLocaleString()}` },
  ], y);
  y = drawFieldRow(doc, [
    { label: 'DESCRIPTION OF OPERATIONS', value: data.businessInfo?.descriptionOfOperations || '' },
  ], y);

  // Prior Carrier
  y = drawSectionHeader(doc, 'Prior Carrier Information', y);
  y = drawFieldRow(doc, [
    { label: 'CARRIER NAME', value: data.priorCarrier?.name || '' },
    { label: 'POLICY NUMBER', value: data.priorCarrier?.policyNumber || '' },
  ], y);
  y = drawFieldRow(doc, [
    { label: 'EXPIRATION DATE', value: data.priorCarrier?.expirationDate || '' },
    { label: 'ANNUAL PREMIUM', value: `$${(data.priorCarrier?.totalPremium || 0).toLocaleString()}` },
    { label: 'YEARS WITH CARRIER', value: String(data.priorCarrier?.yearsWithCarrier || '') },
  ], y);

  // Lines of Business
  if (data.linesRequested?.length > 0) {
    y = drawSectionHeader(doc, 'Lines of Business Requested', y);
    const colWidths = [80, 50, 60];
    y = drawTableHeader(doc, ['LINE OF BUSINESS', 'CURRENT PREMIUM', 'REQUESTED'], y, colWidths);
    data.linesRequested.forEach((line: any) => {
      y = drawTableRow(doc, [
        line.line || '',
        `$${(line.currentPremium || 0).toLocaleString()}`,
        line.requested ? 'YES' : 'NO',
      ], y, colWidths);
    });
  }

  // Loss History
  if (data.lossHistory?.length > 0) {
    y = drawSectionHeader(doc, 'Loss History (5 Years)', y);
    const colWidths = [25, 30, 25, 45, 65];
    y = drawTableHeader(doc, ['YEAR', 'LINE', 'CLAIMS', 'TOTAL INCURRED', 'DESCRIPTION'], y, colWidths);
    data.lossHistory.forEach((loss: any) => {
      y = drawTableRow(doc, [
        String(loss.year || ''),
        loss.line || '',
        String(loss.claims || '0'),
        `$${(loss.totalIncurred || 0).toLocaleString()}`,
        loss.description || '',
      ], y, colWidths);
    });
  }

  drawFooter(doc);
  doc.save('ACORD-125-Commercial-Application.pdf');
}

// ===== ACORD 126 - COMMERCIAL GENERAL LIABILITY =====
export function generateAcord126PDF(data: any): void {
  if (!data) return;
  const doc = new jsPDF();
  let y = drawFormHeader(doc, '126', 'COMMERCIAL GENERAL LIABILITY SECTION');

  y = drawSectionHeader(doc, 'Classification', y);
  y = drawFieldRow(doc, [
    { label: 'GL CLASSIFICATION CODE', value: data.classification?.code || '' },
    { label: 'DESCRIPTION', value: data.classification?.description || '' },
  ], y);
  y = drawFieldRow(doc, [
    { label: 'GROSS RECEIPTS', value: `$${(data.classification?.grossReceipts || 0).toLocaleString()}` },
    { label: 'LIQUOR RECEIPTS', value: `$${(data.classification?.liquorReceipts || 0).toLocaleString()}` },
  ], y);

  y = drawSectionHeader(doc, 'Limits of Insurance', y);
  y = drawFieldRow(doc, [
    { label: 'EACH OCCURRENCE', value: `$${(data.limitsRequested?.eachOccurrence || 0).toLocaleString()}` },
    { label: 'GENERAL AGGREGATE', value: `$${(data.limitsRequested?.generalAggregate || 0).toLocaleString()}` },
  ], y);
  y = drawFieldRow(doc, [
    { label: 'PRODUCTS/COMP OPS AGG', value: `$${(data.limitsRequested?.productsCompletedOpsAggregate || 0).toLocaleString()}` },
    { label: 'PERSONAL & ADV INJURY', value: `$${(data.limitsRequested?.personalAdvertisingInjury || 0).toLocaleString()}` },
  ], y);
  y = drawFieldRow(doc, [
    { label: 'DAMAGE TO RENTED PREMISES', value: `$${(data.limitsRequested?.damageToRentedPremises || 0).toLocaleString()}` },
    { label: 'MEDICAL EXPENSE', value: `$${(data.limitsRequested?.medicalExpense || 0).toLocaleString()}` },
  ], y);

  if (data.liquorLiability) {
    y = drawSectionHeader(doc, 'Liquor Liability', y);
    y = drawFieldRow(doc, [
      { label: 'INCLUDED', value: data.liquorLiability.included ? 'YES' : 'NO' },
      { label: 'LIQUOR SALES %', value: `${data.liquorLiability.liquorSalesPercentage || 0}%` },
    ], y);
    y = drawFieldRow(doc, [
      { label: 'EACH OCCURRENCE', value: `$${(data.liquorLiability.eachOccurrence || 0).toLocaleString()}` },
      { label: 'AGGREGATE', value: `$${(data.liquorLiability.aggregate || 0).toLocaleString()}` },
    ], y);
  }

  if (data.additionalCoverages?.length > 0) {
    y = drawSectionHeader(doc, 'Additional Coverages', y);
    data.additionalCoverages.forEach((cov: any) => {
      y = checkPage(doc, y, 10);
      doc.setFontSize(9);
      doc.text(`☑  ${typeof cov === 'string' ? cov : cov.name || JSON.stringify(cov)}`, 14, y);
      y += 7;
    });
  }

  drawFooter(doc);
  doc.save('ACORD-126-General-Liability.pdf');
}

// ===== ACORD 140 - PROPERTY SECTION =====
export function generateAcord140PDF(data: any): void {
  if (!data) return;
  const doc = new jsPDF();
  let y = drawFormHeader(doc, '140', 'PROPERTY SECTION');

  y = drawSectionHeader(doc, 'Property Summary', y);
  y = drawFieldRow(doc, [
    { label: 'TOTAL BUILDING VALUE', value: `$${(data.totalBuildingValue || 0).toLocaleString()}` },
    { label: 'TOTAL CONTENTS VALUE', value: `$${(data.totalContentsValue || 0).toLocaleString()}` },
    { label: 'BUSINESS INCOME LIMIT', value: `$${(data.totalBILimit || 0).toLocaleString()}` },
  ], y);
  y = drawFieldRow(doc, [
    { label: 'DEDUCTIBLE', value: `$${(data.deductible || 0).toLocaleString()}` },
    { label: 'VALUATION', value: data.valuation || '' },
    { label: 'COINSURANCE', value: data.coinsurance || '' },
  ], y);

  if (data.locations?.length > 0) {
    y = drawSectionHeader(doc, 'Schedule of Locations', y);
    data.locations.forEach((loc: any, i: number) => {
      y = checkPage(doc, y, 40);
      // Location sub-header
      doc.setFontSize(8);
      doc.setFont('helvetica', 'bold');
      doc.setTextColor(0, 51, 102);
      doc.text(`LOCATION #${loc.number || i + 1}: ${loc.address || ''}`, 14, y);
      doc.setTextColor(0, 0, 0);
      y += 6;
      
      y = drawFieldRow(doc, [
        { label: 'BUILDING VALUE', value: `$${(loc.buildingValue || 0).toLocaleString()}` },
        { label: 'CONTENTS VALUE', value: `$${(loc.contentsValue || 0).toLocaleString()}` },
        { label: 'BI LIMIT', value: `$${(loc.biLimit || 0).toLocaleString()}` },
      ], y);
      y = drawFieldRow(doc, [
        { label: 'CONSTRUCTION', value: loc.construction || '' },
        { label: 'YEAR BUILT', value: String(loc.yearBuilt || '') },
        { label: 'SQ FOOTAGE', value: (loc.sqFootage || 0).toLocaleString() },
      ], y);
      y = drawFieldRow(doc, [
        { label: 'STORIES', value: String(loc.stories || '') },
        { label: 'SPRINKLERED', value: loc.sprinklered ? 'YES' : 'NO' },
        { label: 'PROTECTION CLASS', value: loc.protectionClass || '' },
      ], y);
      y += 4;
    });
  }

  drawFooter(doc);
  doc.save('ACORD-140-Property-Section.pdf');
}

// ===== ACORD 130 - WORKERS COMPENSATION =====
export function generateAcord130PDF(data: any): void {
  if (!data) return;
  const doc = new jsPDF();
  let y = drawFormHeader(doc, '130', "WORKERS COMPENSATION APPLICATION");

  y = drawSectionHeader(doc, 'Policy Information', y);
  y = drawFieldRow(doc, [
    { label: 'STATE', value: data.state || '' },
    { label: 'TOTAL ANNUAL PAYROLL', value: `$${(data.totalPayroll || 0).toLocaleString()}` },
  ], y);
  y = drawFieldRow(doc, [
    { label: 'ESTIMATED ANNUAL PREMIUM', value: `$${(data.totalPremium || 0).toLocaleString()}` },
    { label: 'EXPERIENCE MODIFICATION RATE', value: String(data.emr || '') },
    { label: 'DEDUCTIBLE', value: `$${(data.deductible || 0).toLocaleString()}` },
  ], y);

  if (data.classificationCodes?.length > 0) {
    y = drawSectionHeader(doc, 'Classification Codes', y);
    const colWidths = [25, 60, 40, 25, 40];
    y = drawTableHeader(doc, ['CODE', 'DESCRIPTION', 'PAYROLL', 'RATE', 'PREMIUM'], y, colWidths);
    data.classificationCodes.forEach((cls: any) => {
      y = drawTableRow(doc, [
        cls.code || '',
        cls.description || '',
        `$${(cls.payroll || 0).toLocaleString()}`,
        String(cls.rate || ''),
        `$${(cls.premium || 0).toLocaleString()}`,
      ], y, colWidths);
    });
  }

  drawFooter(doc);
  doc.save('ACORD-130-Workers-Compensation.pdf');
}

// ===== ALL FORMS COMBINED =====
export function generateAllAcordPDFs(formData: any): void {
  if (!formData) return;
  if (formData.acord125) generateAcord125PDF(formData.acord125);
  if (formData.acord126) generateAcord126PDF(formData.acord126);
  if (formData.acord140) generateAcord140PDF(formData.acord140);
  if (formData.acord130) generateAcord130PDF(formData.acord130);
}
