import jsPDF from 'jspdf';

function addHeader(doc: jsPDF, formNumber: string, formName: string) {
  doc.setFontSize(16);
  doc.setFont('helvetica', 'bold');
  doc.text(`ACORD ${formNumber} — ${formName}`, 20, 20);
  
  doc.setFontSize(8);
  doc.setFont('helvetica', 'normal');
  doc.text('Generated by SubmissionAI', 200, 10, { align: 'right' });
  doc.text(new Date().toLocaleDateString(), 200, 15, { align: 'right' });
  
  return 30; // Starting Y position for content
}

function addSection(doc: jsPDF, title: string, y: number): number {
  doc.setFontSize(12);
  doc.setFont('helvetica', 'bold');
  doc.text(title, 20, y);
  doc.setLineWidth(0.5);
  doc.line(20, y + 2, 190, y + 2);
  return y + 10;
}

function addField(doc: jsPDF, label: string, value: string, y: number, x: number = 20): number {
  doc.setFontSize(9);
  doc.setFont('helvetica', 'normal');
  doc.setTextColor(100, 100, 100);
  doc.text(`${label}:`, x, y);
  
  doc.setTextColor(0, 0, 0);
  doc.setFont('helvetica', 'normal');
  const lines = doc.splitTextToSize(value || 'N/A', 80);
  doc.text(lines, x + 60, y);
  
  return y + (lines.length * 5) + 3;
}

function addTable(doc: jsPDF, headers: string[], rows: any[][], y: number): number {
  doc.setFontSize(8);
  doc.setFont('helvetica', 'bold');
  
  // Headers
  let x = 20;
  const colWidth = (190 - 20) / headers.length;
  headers.forEach((header, i) => {
    doc.text(header, x + (i * colWidth), y);
  });
  
  doc.setLineWidth(0.3);
  doc.line(20, y + 2, 190, y + 2);
  
  y += 8;
  doc.setFont('helvetica', 'normal');
  
  // Rows
  rows.forEach(row => {
    row.forEach((cell, i) => {
      doc.text(String(cell || ''), x + (i * colWidth), y);
    });
    y += 6;
  });
  
  return y + 5;
}

export function generateAcord125PDF(data: any): void {
  const doc = new jsPDF();
  let y = addHeader(doc, '125', 'Commercial Insurance Application');
  
  // Agency Information
  y = addSection(doc, 'Agency Information', y);
  if (data.sections) {
    const agencySection = data.sections.find((s: any) => s.name === 'Agency Information');
    if (agencySection?.fields) {
      agencySection.fields.forEach((field: any) => {
        y = addField(doc, field.label, field.value, y);
      });
    }
  }
  y += 5;
  
  // Named Insured
  y = addSection(doc, 'Named Insured', y);
  const insuredSection = data.sections?.find((s: any) => s.name === 'Named Insured');
  if (insuredSection?.fields) {
    insuredSection.fields.forEach((field: any) => {
      y = addField(doc, field.label, field.value, y);
    });
  }
  y += 5;
  
  // Business Information
  y = addSection(doc, 'Business Information', y);
  const businessSection = data.sections?.find((s: any) => s.name === 'Business Information');
  if (businessSection?.fields) {
    businessSection.fields.forEach((field: any) => {
      y = addField(doc, field.label, field.value, y);
      if (y > 270) {
        doc.addPage();
        y = 20;
      }
    });
  }
  y += 5;
  
  // Prior Carrier
  if (y > 240) {
    doc.addPage();
    y = 20;
  }
  y = addSection(doc, 'Prior Carrier', y);
  const priorSection = data.sections?.find((s: any) => s.name === 'Prior Carrier');
  if (priorSection?.fields) {
    priorSection.fields.forEach((field: any) => {
      y = addField(doc, field.label, field.value, y);
    });
  }
  
  doc.save('ACORD-125-Application.pdf');
}

export function generateAcord126PDF(data: any): void {
  const doc = new jsPDF();
  let y = addHeader(doc, '126', 'Commercial General Liability');
  
  // GL Classification
  y = addSection(doc, 'General Liability Classification', y);
  const classSection = data.sections?.find((s: any) => s.name.includes('Classification'));
  if (classSection?.fields) {
    classSection.fields.forEach((field: any) => {
      y = addField(doc, field.label, field.value, y);
    });
  }
  y += 5;
  
  // Limits Requested
  y = addSection(doc, 'Limits Requested', y);
  const limitsSection = data.sections?.find((s: any) => s.name.includes('Limits'));
  if (limitsSection?.fields) {
    limitsSection.fields.forEach((field: any) => {
      y = addField(doc, field.label, field.value, y);
      if (y > 270) {
        doc.addPage();
        y = 20;
      }
    });
  }
  y += 5;
  
  // Liquor Liability
  if (y > 240) {
    doc.addPage();
    y = 20;
  }
  y = addSection(doc, 'Liquor Liability', y);
  const liquorSection = data.sections?.find((s: any) => s.name.includes('Liquor'));
  if (liquorSection?.fields) {
    liquorSection.fields.forEach((field: any) => {
      y = addField(doc, field.label, field.value, y);
    });
  }
  y += 5;
  
  // Additional Coverages
  y = addSection(doc, 'Additional Coverages', y);
  const coveragesSection = data.sections?.find((s: any) => s.name.includes('Additional'));
  if (coveragesSection?.fields) {
    coveragesSection.fields.forEach((field: any) => {
      y = addField(doc, field.label, field.value, y);
    });
  }
  
  doc.save('ACORD-126-General-Liability.pdf');
}

export function generateAcord130PDF(data: any): void {
  const doc = new jsPDF();
  let y = addHeader(doc, '130', 'Workers Compensation Application');
  
  // WC Summary
  y = addSection(doc, 'Workers Compensation Summary', y);
  const summarySection = data.sections?.find((s: any) => s.name.includes('Summary'));
  if (summarySection?.fields) {
    summarySection.fields.forEach((field: any) => {
      y = addField(doc, field.label, field.value, y);
    });
  }
  y += 10;
  
  // Classification Codes Table
  if (y > 200) {
    doc.addPage();
    y = 20;
  }
  y = addSection(doc, 'Classification Codes', y);
  const classSection = data.sections?.find((s: any) => s.name.includes('Classification'));
  if (classSection?.fields && classSection.fields.length > 0) {
    const tableData = classSection.fields.map((f: any) => [
      f.code || '',
      f.description || f.label || '',
      f.payroll || '',
      f.rate || '',
      f.premium || ''
    ]);
    y = addTable(doc, ['Code', 'Description', 'Payroll', 'Rate', 'Premium'], tableData, y);
  }
  
  doc.save('ACORD-130-Workers-Comp.pdf');
}

export function generateAcord140PDF(data: any): void {
  const doc = new jsPDF();
  let y = addHeader(doc, '140', 'Property Section');
  
  // Property Summary
  y = addSection(doc, 'Property Summary', y);
  const summarySection = data.sections?.find((s: any) => s.name.includes('Summary'));
  if (summarySection?.fields) {
    summarySection.fields.forEach((field: any) => {
      y = addField(doc, field.label, field.value, y);
    });
  }
  y += 10;
  
  // Locations Table
  if (y > 180) {
    doc.addPage();
    y = 20;
  }
  y = addSection(doc, 'Locations', y);
  const locationsSection = data.sections?.find((s: any) => s.name.includes('Locations'));
  if (locationsSection?.fields && locationsSection.fields.length > 0) {
    const tableData = locationsSection.fields.map((f: any) => [
      f.address || f.label || '',
      f.building_value || '',
      f.contents_value || '',
      f.construction || '',
      f.sprinklered ? 'Yes' : 'No'
    ]);
    y = addTable(doc, ['Address', 'Building', 'Contents', 'Construction', 'Sprinkler'], tableData, y);
  }
  
  doc.save('ACORD-140-Property.pdf');
}

export function generateAllAcordPDFs(formData: any): void {
  const doc = new jsPDF();
  let y = 20;
  
  // Cover Page
  doc.setFontSize(20);
  doc.setFont('helvetica', 'bold');
  doc.text('ACORD Forms Package', 105, 60, { align: 'center' });
  
  doc.setFontSize(12);
  doc.setFont('helvetica', 'normal');
  doc.text('Commercial Insurance Submission', 105, 75, { align: 'center' });
  doc.text(`Generated: ${new Date().toLocaleDateString()}`, 105, 85, { align: 'center' });
  doc.text('Generated by SubmissionAI', 105, 95, { align: 'center' });
  
  // ACORD 125
  if (formData.acord125) {
    doc.addPage();
    y = addHeader(doc, '125', 'Commercial Insurance Application');
    
    formData.acord125.sections?.forEach((section: any) => {
      if (y > 250) {
        doc.addPage();
        y = 20;
      }
      y = addSection(doc, section.name, y);
      section.fields?.forEach((field: any) => {
        y = addField(doc, field.label, field.value, y);
        if (y > 270) {
          doc.addPage();
          y = 20;
        }
      });
      y += 5;
    });
  }
  
  // ACORD 126
  if (formData.acord126) {
    doc.addPage();
    y = addHeader(doc, '126', 'Commercial General Liability');
    
    formData.acord126.sections?.forEach((section: any) => {
      if (y > 250) {
        doc.addPage();
        y = 20;
      }
      y = addSection(doc, section.name, y);
      section.fields?.forEach((field: any) => {
        y = addField(doc, field.label, field.value, y);
        if (y > 270) {
          doc.addPage();
          y = 20;
        }
      });
      y += 5;
    });
  }
  
  // ACORD 130
  if (formData.acord130) {
    doc.addPage();
    y = addHeader(doc, '130', 'Workers Compensation Application');
    
    formData.acord130.sections?.forEach((section: any) => {
      if (y > 250) {
        doc.addPage();
        y = 20;
      }
      y = addSection(doc, section.name, y);
      section.fields?.forEach((field: any) => {
        y = addField(doc, field.label, field.value, y);
        if (y > 270) {
          doc.addPage();
          y = 20;
        }
      });
      y += 5;
    });
  }
  
  // ACORD 140
  if (formData.acord140) {
    doc.addPage();
    y = addHeader(doc, '140', 'Property Section');
    
    formData.acord140.sections?.forEach((section: any) => {
      if (y > 250) {
        doc.addPage();
        y = 20;
      }
      y = addSection(doc, section.name, y);
      section.fields?.forEach((field: any) => {
        y = addField(doc, field.label, field.value, y);
        if (y > 270) {
          doc.addPage();
          y = 20;
        }
      });
      y += 5;
    });
  }
  
  doc.save('ACORD-Forms-Complete-Package.pdf');
}
